### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by ledjajev** [GeorgiyDemo/AliceVK#2]
C:\Users\user\Desktop\vk.bot\alice\AliceVK>python Alice.py
Traceback (most recent call last):
  File "Alice.py", line 168, in <module>
    birthday_all = get_bdate_chat()
  File "Alice.py", line 154, in get_bdate_chat
    chat_user_arr=api.messages.getChat(chat_id=conversations[str(chat_id+1)],fields='bdate',v=APIVersion)['users']
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vk\api.py", line 173, in __call__
    return self._api._session.make_request(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vk\api.py", line 102, in make_request
    raise error
vk.exceptions.VkAPIError: 5. User authorization failed: method is unavailable with group auth.. request_params = {'oauth': '1', 'method': 'messages.getChat', 'chat_id': '14', 'fields': 'bdate', 'v': '5.73'}

**Comment by GeorgiyDemo** [comment]
Привет, ты вызываешь авторизацию с токеном сообщества, а этот бот использует методы с авторизацией пользователя.
Для авторизации пользователя требуется создать standalone-приложение или использовать чье-то другое (пример: https://vk.cc/6Y5h7G)
